### ISSUE TITLE
Gtk-Message: 14:58:51.829: Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by ccshao** [syco/io.typora.flatpak#1]
Thanks for the flatpak version, however, in XFAC, when run in terminal

` flatpak run io.typora.flatpak`

I get the message:

> Gtk-Message: 14:58:51.829: Failed to load module "canberra-gtk-module"

Any ideas on how to fix it?

**Comment by syco** [comment]
Hi,
I have this problem with many applications.
Something is broken in libcanberra and gtk, but it's just a warning and should be safe to ignore.
If the flatpak is not working for you there must be some other more important error.

Depending on your distribution you might be able to fix this warning by installing some or all the "libcanberra-gtk*" packages.
But I tested this theory myself on opensuse and it didn't work. But the flatpak still works as normal.

**Comment by ccshao** [comment]
Thanks for the quick reply. Indeed, although typora wont starts by clicking the icon, it works from terminal. I created a launcher for clicking.

**Comment by syco** [comment]
Hi,
I checked why the launcher wouldn't work and turns out there was an issue with the Exec line.
I've fixed it in the latest release [v0.9.89-1](https://github.com/syco/io.typora.flatpak/releases/tag/v0.9.89-1)

**Comment by ccshao** [comment]
Thanks,  Now it works nicely as expected!
________________________________
