### ISSUE TITLE
Default flatpak config gives access to too many system resources

### ISSUE THREAD

**Issue by inferont** [syco/io.typora.flatpak#3]
**Describe the bug**
This is a closed-source proprietary program. We do not know what it is doing with our sensitive documents. The purpose of flatpak is to sandbox our applications for better security and privacy. The current default does not do this.

**To Reproduce**
Install a program like Flatseal, see that Typora has access to full filesystem, network, and devices.

**Expected behavior**
Should only have access to the users home folder at most, maybe ~/Documents at minimum.

**Comment by syco** [comment]
Hi,
I'm aware of that, but I (for example) need typora to have access to files in external hd and other partitions, not just in the home or document folder.
However, flatpak allows individual users to override this setting.
Have a look at [](https://manpages.debian.org/testing/flatpak/flatpak-override.1.en.html)

**Comment by inferont** [comment]
I think I would be okay letting Typora have access to files as long as it didn't have access to the network. I just think the default permissions should be bare minimum here.

**Comment by syco** [comment]
I agree with that, I just never took the time to validate if `--share=network` was actaully needed for typora to function properly, I just assumed that if you wanted to attach some content from the web it was required.
The other one I'm not sure of is `--socket=pulseaudio`.

If you can confirm what's not needed, I'll publish a new updated release.

**Comment by inferont** [comment]
I have almost everything disabled for Typora via Flatseal and it works fine. 

1. (--share=network) It looks like there's some weird image upload option in the menu that would not work without network support. It requires some shell knowledge to properly setup and the default setup does not work at the moment. If someone uses this feature I think they could re-enable network support?

2. Pulseaudio (audio access) can surely be disabled.

These are my settings:
![typora flatseal 1](https://user-images.githubusercontent.com/12887855/95129321-7b112080-0720-11eb-8b19-cad2f0d7e163.png)

![typora flatseal 1](https://user-images.githubusercontent.com/12887855/95129341-7fd5d480-0720-11eb-8f16-d056a3183def.png)

**Comment by syco** [comment]
'morning (at least here is morning), I've removed network and pulseaudio permissions.
And uploaded 0.9.96-2
